{{- $listeners := include "nautiluslb.listeners" . | fromJsonArray }}
{{- if and .Values.service.enabled (not .Values.hostNetwork) $listeners }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nautiluslb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nautiluslb.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "nautiluslb.selectorLabels" . | nindent 4 }}
  {{- if and .Values.service.externalTrafficPolicy (ne .Values.service.type "ClusterIP") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    {{- range $listeners }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      {{- if and .nodePort (ne $.Values.service.type "ClusterIP") }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
{{- end }}
